language: node_js
node_js:
  - "8.11.1"
cache: yarn
branches:
  only:
  - develop
install:
  - npm install -g firebase-tools
  - yarn

script:
  - yarn lint
  - yarn build
after_success:
- firebase use --token ${FIREBASE_TOKEN}
- firebase use --add ${PROJECT_ID}
- firebase deploy --non-interactive --token "${FIREBASE_TOKEN}"