export const FETCH_SINGLE_EVENT = 'FETCH_SINGLE_EVENT';
export const FETCH_MULTI_EVENT = 'FETCH_MULTI_EVENT';
export const FETCH_EVENTS_PENDING = 'FETCH_EVENTS_PENDING';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';
