#import "../fragments/EventFragment.gql"

# query Events ($startedAt: String, $limit: Int) {
query Events($startedAt: String, $limit: Int) {
  events (startedAt: $startedAt, limit: $limit) {
    ...Event
  }
}